[package]
name = "dca-rs"
version = "0.1.0"
authors = ["Nicholas Stafie <nicholasstafie@gmail.com>"]

[dependencies]
clap = "2.1.2"
opus = { path = "lib/opus-rs" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
byteorder = "0.5.0"
